sudo: required
language: bash
env:
  global:
    - BUILD_NAME=IC2020
services:
  - docker
git:
  depth: false
before_install:
  - openssl aes-256-cbc -K $encrypted_d4473614101c_key -iv $encrypted_d4473614101c_iv -in ci/config -out config.tar -d
  - tar xvf config.tar
  - export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
  - rm Unity_v2018.x.ulf
  - docker pull $IMAGE_NAME
branches:
  only:
    - master
    - "/^integ\\..*$/"
    - "/^preprod\\..*$/"
    - "/^prod\\..*$/"
    - Sogo-deploy
jobs:
  include:
    - stage: build
      name: Build WebGL
      env: BUILD_TARGET=WebGL
      script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: Builds/WebGL
    target_branch: pages-sogo
    on:
      repo: lbhs/IC2020
      branch: Sogo-deploy
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: Builds/WebGL
    target_branch: pages-preprod
    on:
      repo: lbhs/IC2020
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: Builds/WebGL
    target_branch: pages-integ
    on:
      all_branches: true
      tag: true
      repo: lbhs/IC2020
      condition: "$TRAVIS_TAG =~ ^integ\\..*$"
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: Builds/WebGL
    target_branch: pages-preprod
    on:
      all_branches: true
      tag: true
      repo: lbhs/IC2020
      condition: "$TRAVIS_TAG =~ ^preprod\\..*$"
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: Builds/WebGL
    target_branch: pages-prod
    on:
      all_branches: true
      tag: true
      repo: lbhs/IC2020
      condition: "$TRAVIS_TAG =~ ^prod\\..*$"
after_deploy:
  - chmod +x ./ci/post_deploy.sh && ./ci/post_deploy.sh 
